### ISSUE TITLE
Keyframes Animations

### ISSUE THREAD

**Issue by Wixonic** [Cryptic-Techs/Donut#11]
- [ ] : **Add** keyframes animations in Donut

Idea by @Stefan-ci

**Comment by Wixonic** [comment]
> First of all, we may create a class "3D" then "text" or "objects" or something else.
> 
> (
> 
> Text here....
> )
> Like this

A class ?

If it was in JavaScript, never create that because **Donut** is a pure CSS framework.

**Comment by Wixonic** [comment]
> First of all, we may create a class "3D" then "text" or "objects" or something else like this:
> 
> `<div class="3D-text> Text here... </div>`
> 
> `<div class="3D-object"> Object </div>`

Sorry.. I don't understand..

**Comment by Wixonic** [comment]
> > > First of all, we may create a class "3D" then "text" or "objects" or something else like this:
> > > `<div class="3D-text> Text here... </div>`
> > > `<div class="3D-object"> Object </div>`
> > 
> > 
> > Sorry.. I don't understand..
> 
> @Wixonic We may specify a class name `3D-text` and simply animate it.
> For objects and so on, we may add `3D-object` instead of - - `3D-text`

Oh ok !

**Comment by Wixonic** [comment]
```css
@keyframes fade
{
    from {opacity: 1;}
    to {opacity: 0;}
}
```

@Stefan-ci maybe a simple animation ?
And later more complexes ?

**Comment by Wixonic** [comment]
A fall animation ?

```css
@keyframes fall
{
	0% {transform: translateY(-100px);}
	8% {transform: translateY(-98px);}
	12% {transform: translateY(-95px);}
	15% {transform: translateY(-91px);}
	19% {transform: translateY(-86px);}
	23% {transform: translateY(-80px);}
	26% {transform: translateY(-73px);}
	30% {transform: translateY(-65px);}
	34% {transform: translateY(-56px);}
	37% {transform: translateY(-46px);}
	41% {transform: translateY(-35px);}
	45% {transform: translateY(-23px);}
	48% {transform: translateY(-10px);}
	52% {transform: translateY(4px);}
	56% {transform: translateY(19px);}
	59% {transform: translateY(35px);}
	63% {transform: translateY(52px);}
	67% {transform: translateY(70px);}
	70% {transform: translateY(90px)}
	85% {transform: translateY(100px) scale(1.1,0.7)}
	100% {transform: translateY(100px) scale(1.3,0.3)}
}
```
